### ISSUE TITLE
Port to PyQt5

### ISSUE THREAD

**Issue by a17r** [alexisflesch/texamator#1]
Are there any plans to port this codebase to PyQt5? At this point, distributions are busy cleaning up Qt4 reverse-dependencies everywhere, and e.g. KDE is going to release Applications 17.12 in December without any non-ported packages  - okular is Qt5-based for some time.

**Comment by alexisflesch** [comment]
I would like to port it to Python3/Qt5 but a lack of talent/motivation/time is blocking the effort. I shall ask on the forums for people with the right knowledge to help me port it.

**Comment by alexisflesch** [comment]
Work now in progress : alpha release coming by the end of the summer.

**Comment by alexisflesch** [comment]
Alpha version commited here :
https://github.com/alexisflesch/texamator/tree/python3-qt5-alpha

As the name suggests, it's been ported to python3 and Qt5.

Okular has been dropped and TeXamator is now using its own pdf viewer based on poppler.
