### ISSUE TITLE
Cannot run texamator

### ISSUE THREAD

**Issue by jdaniel5** [alexisflesch/texamator#4]
Hi,

I am trying to run Texamator and get the following error message : 
```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
libpng warning: iCCP: known incorrect sRGB profile
Traceback (most recent call last):
  File "/home/jeremy/Téléchargements/texamator-master/texamator.py", line 1260, in <module>
    ui.setupUi2(MainWindow)
  File "/home/jeremy/Téléchargements/texamator-master/texamator.py", line 1234, in setupUi2
    self.tableWidget.setColumnWidth(0,.6*l1[1])
TypeError: setColumnWidth(self, int, int): argument 2 has unexpected type 'float'
```
I have tried to replace
`self.tableWidget.setColumnWidth(0,.6*l1[1])`
by 
`self.tableWidget.setColumnWidth(0,int(.6*l1[1]))`
Then, I can run Texamator. However, I get the following errors :
`Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
couldn't create texamator dir or texamator dir already exists
libpng warning: iCCP: known incorrect sRGB profile
Couldn't open/home/jeremy/Bureau/Test Info/TD/20_b_dénombrement.tex
`
and the same errors with all .tex files. 
Also, when I click on "Preferences", I get the following error : 
```
Traceback (most recent call last):
  File "/home/jeremy/Téléchargements/texamator-master/texamator.py", line 636, in prefs
    guiprefsplus.updateUi(self, MyHighlighter)
  File "/home/jeremy/Téléchargements/texamator-master/partielatormods/guis/guiprefsplus.py", line 59, in updateUi
    self.last_generate = keys[0]                    #config being displayed
IndexError: list index out of range
```
I'm on Ubuntu 22.04 and Python 3.10.4.

Thank you for your help!

**Comment by alexisflesch** [comment]
Hi,

The first error is due to a newer version of a library, I think you did what needed to be done on that end.

Could you please try to move texamator-master outside the Téléchargements folder, remove /home/jeremy/.texamator and give it another try ? There might be an issue with non-ascii paths.

**Comment by jdaniel5** [comment]
I have changed the location of texamator but unfortunately that doesn't work.
There was an encoding problem with the .tex files. I have fixed that and now, the Wizard works (it guesses the \begin{exo} and \end{exo} and the preamble). When I ask to look for Exercises, nothing happens (no error ; but it doesn't find anything). And still the same error when clicking on "Preferences"

**Comment by alexisflesch** [comment]
Could you please upload somewhere your folder .texamator which should be located in /home/jeremy ? Btw, have you tried removing it and re-running texamator ?

I can also send you my preferences in order to rule that out. I'll test things on my end when I have some free time : I'm used to keeping my preferences from one install to another and the error might be coming from one of texamator's updates.

**Comment by jdaniel5** [comment]
[texamator-master.zip](https://github.com/alexisflesch/texamator/files/8933802/texamator-master.zip)

I have compressed the folder. The only modification I made is about the float/int problem. 
Yes, I have tried removing and re-running, but nothing changes.

Thank you for your help!

**Comment by alexisflesch** [comment]
I'm actually looking for the (hidden) folder `/home/jeremy/.texamator` which contains your preferences where the problem seems to be coming from. This is the one you should remove before restarting texamator : it might fix your issue.

**Comment by jdaniel5** [comment]
Oh sorry, I am new to Ubuntu :)
I have removed the hidden folder and ... that worked! Thanks again; I am sure that I will save some time with your program!
