### ISSUE TITLE
Problème installation sur ubuntu 22.04

### ISSUE THREAD

**Issue by Fklag** [alexisflesch/texamator#5]
Bonjour,

Je viens de mettre à jour ma distribution vers ubuntu 22.04.
Pour l'installation de TeXamator je pars des fichiers ici : [https://github.com/alexisflesch/texamator](https://github.com/alexisflesch/texamator)

Pour l'install je suis bien passé par les commandes :
```
sudo apt-get install -y python3-poppler-qt5
sudo apt-get install -y python3-pyqt5
```

Quand je lance la commande : `python3 texamator.py` j'ai eu un premier pb de type `float`(??) alors j'ai modifié la ligne 1234 du fichier texamator.py
`self.tableWidget.setColumnWidth(0,int(.6*l1[1])) # ici pas de int sur fichier origine`

Je peux alors lancé TeXamator et j'ai le message : "libpng warning: iCCP: known incorrect sRGB profile" (une recherche rapide sur internet me donne quelques commandes pour modifier le profil des images .png mais cela n'aboutit pas chez moi... je laisse tomber car l'interface graphique se lance quand même)

Le pb est que le programme semble buggé pour certaines fonctionnalités (je peux changer de langue) par exemple lorsque j'essaie de modifier à l'aide du menu les "préférences" j'ai le message d'erreur :

```
Traceback (most recent call last):
  File "/home/fk/texamator-master/texamator.py", line 636, in prefs
    guiprefsplus.updateUi(self, MyHighlighter)
  File "/home/fk/texamator-master/partielatormods/guis/guiprefsplus.py", line 59, in updateUi
    self.last_generate = keys[0]                    #config being displayed
IndexError: list index out of range
```

Que puis-je faire pour installer proprement TeXamator sur ubuntu 22.04 ?

Merci d'avance.
Bonne journée,
Franck Lagrave

**Comment by alexisflesch** [comment]
Bonjour,

La première erreur est de ma faute : une librairie a été modifiée et je n'ai pas encore fait les changements nécessaires mais vous l'avez fait de votre côté.

Le message d'avertissement de libpng est sans conséquence, vous pouvez l'ignorer.

Pour le reste, cela peut simplement venir du dossier dans lequel vous avez copié texamator : serait-ce dans Téléchargements ? Si oui, les accents sont à l'origine du problème pour une raison qui m'échappe.

Essayez alors de copier le logiciel à la racine de votre home puis supprimez le dossier caché ".texamator" qui s'y trouve pour repartir de zéro (il contient vos préférences et il est créé automatiquement au démarrage).

Tenez-moi au courant, si ça vient de là il faudra que je mette à jour le readme car c'est un problème récurrent.

**Comment by Fklag** [comment]
Nickel ! Il fallait bien supprimer le dossier caché ".texamator" et relancer le logiciel !!

D'ailleurs (oups !) je viens de voir l'info dans votre readme ... 
```
Getting started

The first time your run TeXamator, it will start a wizard to help you configure it. If, for some reason, you want to remove all your preferences, just find the folder ".partielator" in your home directory and delete it.
```
Encore merci pour votre réactivié, désolé pour le bruit ...

Bonne fin de journée.

**Comment by Fklag** [comment]
Pour info, j'ai modifié aussi ligne 128 dans /texamator-master/partielatormods/guis/guiprefsplus.py : 

`self.tableWidget.setColumnWidth(0,int(.6*l1)) # ici pas de int sur fichier origine`

Par contre lorsque j'essaie de compiler un exo j'ai le message :

```
"Error: Couldn't open file '/tmp/texamator/file.pdf': Aucun fichier ou dossier de ce type."
Traceback (most recent call last):
  File "/home/fk/texamator-master/texamator.py", line 216, in recompile
    for cmd in self.compile_seq[self.settings["preferred compile sequence"]]['sequence']:
TypeError: list indices must be integers or slices, not str

```

Bizarre, je poursuis ma recherche ...

**Comment by Fklag** [comment]
Bon ça vient de ma compil xelatex en shell-escape ... faut que je regarde de plus près sûrement les caractères spéciaux 
`xelatex -synctex=1 -shell-escape -src -interaction=nonstopmode %.tex`

En compilant par défaut en pdflatex c'est ok !!

**Comment by Fklag** [comment]
Avec file.tex pour la compil ça à l'air bon.

`xelatex -synctex=1 -shell-escape -src -interaction=nonstopmode file.tex`

Merci encore pour ce logiciel.
