### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by A1achilles** [alexisflesch/texamator#6]
Hello. 
Thank you for texamator. It is very helpful for my job(I teach mathematics).
I would like to ask you if it is possible to install texamator on a web server and run it remotely.
Thank you in advance.
Manos

**Comment by alexisflesch** [comment]
Hi,
Sorry for not answering sooner, I didn't get the notification. Short answer : no. Installing it on a remote server would mean a lot of tweaking : the UI is made with Qt, it's not meant to be rendered as an html page.

I have asked myself the same question a while ago, and almost went for a complete rewrite to create a TeXamator web app. The only way this would be worth it would be with an open database : everyone would be able to access all the exercises. The problem would then be about copyrights... And offering one database per user wouldn't make sense in my opinion.

Alexis.

**Comment by A1achilles** [comment]
Ok Alexis. Thank you for the response.
Manos

**Comment by A1achilles** [comment]
Qt

**Comment by A1achilles** [comment]
Ok Alexis ..thank you for the response.
Manos
