### ISSUE TITLE
Dockerize the app?

### ISSUE THREAD

**Issue by AmanSaurav** [alexisflesch/texamator#7]
Hi, would you be open to dockerizing the app? would be useful to everyone to get it up and running immediately, without worrying about dependencies. .

**Comment by alexisflesch** [comment]
Is docker the right choice to run a GUI-based application ? It is my understanding that docker containers are primarily designed for running headless, command-line applications and server-based services.

Plus, texamator only has two dependencies (three if you count LaTeX) so I really don't see why (and how) this would benefit anyone ?

**Comment by AmanSaurav** [comment]
i actually do not know docker well enough to know whether it can or cant run gui apps. 
I dont remember how i had installed texamator on my mac ( i had opened an issue long back). but i cant seem to get it to run again. and even when i did get it running the previous time, it kept crashing for whatever reason.  

finally i installed a virtual box ubuntu today and lo and behold within minutes texamator was up and running. i was hoping there would be a simpler way to run it on a mac, like maybe an ubuntu docker or like a native app perhaps.

**Comment by alexisflesch** [comment]
I think virtual box is a good workaround : I've had a few people telling me the installation of PyQt5 and/or python-poppler was not easy under MacOS. Anyhow, I'm pretty sure docker is not the way.
